# Copyright 2026 The Prism Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license.

source_set("prism_spaces") {
  sources = [
    "prism_spaces_ui.cc",
    "prism_spaces_ui.h",
  ]

  public_deps = [
    "//base",
    "//content/public/browser",
    "//prism:prism",
  ]

  deps = [
    "//chrome/browser:browser_public_dependencies",
    "//chrome/browser/prism:delegate_headers",
  ]
}
