#!/usr/bin/env python3
"""Generate a C++ asset table for a WebUI request filter from a directory of
files. WebUI filters serve bytes without a MIME override; images/fonts are
sniffed by content, so no mime column is needed.

Usage:
  gen_webui_assets.py <namespace> <asset_dir> <out.cc>

Emits <out.cc> with:
  struct {ns}Asset { const char* path; const unsigned char* data; size_t size; };
  const {ns}Asset* Find{ns}Asset(std::string_view path)  // nullptr when absent
"""
import os
import sys

def main():
    namespace, asset_dir, out_path = sys.argv[1], sys.argv[2], sys.argv[3]
    entries = []
    for name in sorted(os.listdir(asset_dir)):
        full = os.path.join(asset_dir, name)
        if os.path.isfile(full):
            entries.append(name)

    parts = []
    parts.append("// Generated by chromium/scripts/gen_webui_assets.py — do not edit.\n")
    parts.append("// Regenerate when assets change; the output is checked in so the\n")
    parts.append("// build stays a plain compile.\n\n")
    parts.append('#include <stddef.h>\n#include <string_view>\n\n')
    parts.append(f"namespace {namespace} {{\n\n")
    parts.append(f"struct {namespace}Asset {{\n")
    parts.append("  const char* path;\n  const unsigned char* data;\n  size_t size;\n};\n\n")
    for name in entries:
        symbol = "k_" + name.replace(".", "_").replace("-", "_")
        data = open(os.path.join(asset_dir, name), "rb").read()
        parts.append(f"const unsigned char {symbol}[] = {{\n")
        for i in range(0, len(data), 16):
            parts.append("    " + ", ".join(str(b) for b in data[i:i+16]) + ",\n")
        parts.append("};\n\n")
    parts.append(f"const {namespace}Asset k{namespace}Assets[] = {{\n")
    for name in entries:
        symbol = "k_" + name.replace(".", "_").replace("-", "_")
        parts.append(f'    {{"{name}", {symbol}, sizeof({symbol})}},\n')
    parts.append("};\n\n")
    parts.append(f"const {namespace}Asset* Find{namespace}Asset(std::string_view path) {{\n")
    parts.append(f"  for (const auto& asset : k{namespace}Assets) {{\n")
    parts.append("    if (path == asset.path) {\n      return &asset;\n    }\n")
    parts.append("  }\n  return nullptr;\n}\n\n")
    parts.append(f"}}  // namespace {namespace}\n")
    open(out_path, "w").write("".join(parts))
    total = sum(os.path.getsize(os.path.join(asset_dir, n)) for n in entries)
    print(f"{out_path}: {len(entries)} assets, {total} bytes payload")

if __name__ == "__main__":
    main()
